### ISSUE TITLE
Allow USB Debugging  is not shown  in the oculus

### ISSUE THREAD

**Issue by IndrawanBudiP** [rail-berkeley/oculus_reader#2]
I had follow the instruction :

1.  Turn on the Developer Mode toggle.
2. Connect your device to your computer using a USB-C cable and then wear the device. ( I used  Ubuntu)

but the  notification Allow USB Debugging  is not shown  in the oculus

is there i miss something..

**Comment by dosssman** [comment]
Hello there.

Not sure if you are still looking, for a fix, or if someone else has the same problem, the window poped up after trying to run `python oculus_reader/readter.py`

**Comment by jborbik** [comment]
This is the correct answer. Thank you @dosssman !
