### ISSUE TITLE
what is the controller coordinate system

### ISSUE THREAD

**Issue by rancheng** [rail-berkeley/oculus_reader#4]
while reading the data from controller, and visualize in `rviz`, the axis is not identity to the default world coordinate (`x: right, y: front, z: up`)
What I observed is like this:
![Weixin Image_20240222101214](https://github.com/rail-berkeley/oculus_reader/assets/2719771/10eeba9e-b86d-4e8e-b161-2ad9b2fc9e20)

what I want is to make the axis of controller aligh with the world coordinate.

**Comment by rancheng** [comment]
after a few trials I found that the coordinate system is relative to the headset, I thought the headset might be the fixed world coordinate, but looks like the headset has it's own pose, so each time the headset orientation changes the controller's axis is also changed, how can I recover the absolute pose relative the real-world coordinate?

**Comment by jborbik** [comment]
We haven't considered it until now. In our usecase we are storing a starting position marked by pressing the button and then calculated relative poses with respect to that. I hope that helps.

If you would have any suggestions for the absolute pose estimation, PR would be helpful!

**Comment by XiaoweiLinXL** [comment]
Hi @jborbik, do you mean the reference frames is decided by pressing a button? Which button is it? I notice that either when I move the controller or the headset, the transformation matrices are changing, so I am confused about what is the reference frame. Thank you!

**Comment by XiaoweiLinXL** [comment]
Hi @rancheng , did you figure out how to do it?

**Comment by JasonKge** [comment]
test
