### ISSUE TITLE
 Failed to parse APK file: /data/local/tmp/teleop-debug.apk]

### ISSUE THREAD

**Issue by tekntrash** [rail-berkeley/oculus_reader#6]
trying to execute python reader.py and getting

ppadb.InstallError: /data/local/tmp/teleop-debug.apk could not be installed - [: Failed to parse APK file: /data/local/tmp/teleop-debug.apk]

I accepted it already in the oculus: if I type adb devices I get List of devices attached 1PASH9B5JV9386  device 

And if I type adb shell ip route I get 192.168.0.0/24 dev wlan0 proto kernel scope link src 192.168.0.53

**Comment by jborbik** [comment]
Thanks for sharing this! Does this happen with Oculus Quest 2 or 3? Are you using the latest commit on the main branch?

**Comment by tekntrash** [comment]
Apparently the problem was not using git-lfs to clone this repo. When using a regular git, it brings in an APK which is practically empty

**Comment by jborbik** [comment]
There is a note about this in the readme. If you follow the git lfs steps before cloning does it resolve your issue?

**Comment by tekntrash** [comment]
yes it does thanks. now trying to get the oculus not to stop working when I remove it from my head

**Comment by jborbik** [comment]
Something simple like putting a piece of tape on the proximity sensor between the lenses inside the headset helps. Besides, change the auto sleep setting of your device.

**Comment by tekntrash** [comment]
Actually the paper solution just drives the oculus mad: what only worked was using Sidequest and disabling the proximity sensor. All other methods failed

**Comment by jborbik** [comment]
Thanks for sharing!
