### ISSUE TITLE
 Issue with Downloading LFS Object: oculus_reader/APK/teleop-debug.apk

### ISSUE THREAD

**Issue by HY-LiYihan** [rail-berkeley/oculus_reader#9]
I'm experiencing a problem while trying to restore the oculus_reader/APK/teleop-debug.apk file from the repository. Here are the details of the issue:

Action Taken: I executed the `git restore --source=HEAD :/` command to restore the repository to its last committed state.

Error Encountered: The process failed while attempting to download the oculus_reader/APK/teleop-debug.apk file. The error message indicates that the repository has exceeded its data quota for Git LFS:
`Error downloading object: oculus_reader/APK/teleop-debug.apk (ea98832): Smudge error: Error downloading oculus_reader/APK/teleop-debug.apk (ea9883294ae6465f09d581d6c50f2939fff00890e4b3ead8316caae83df26341): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.`

**Comment by jborbik** [comment]
See here: https://github.com/rail-berkeley/oculus_reader/issues/7#issuecomment-2452603747. If this issue happens again I'll definitely move the APK from git LFS to git repo.
